controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
info_user:
    path: /info-user
    controller: App\Controller\InfoUserController::index
valider_modifications:
    path: '/valider-modifications'
    controller: 'App\Controller\DefaultController::validerModifications'
