controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
info_user:
    path: /info-user
    controller: App\Controller\InfoUserController::index
api_create_habitant:
    path: /api/create-habitant
    controller: App\Controller\ApiController::createHabitant
    methods: ['POST']
api_modify_habitant:
    path: /api/modify-habitant
    controller: App\Controller\ApiController::modifyHabitant
    methods: ['POST']
api_delete_habitant:
    path: /api/delete-habitant/{id}
    controller: 'App\Controller\ApiController::deleteHabitant'
    methods: ['POST']
form:
    path: /form
    controller: App\Controller\FormController::index

